### ISSUE TITLE
Issue with Django 3

### ISSUE THREAD

**Issue by roukydesbois** [rdkit/django-rdkit#11]
Hello guys,

This import doesn't work anymore in Django 3: https://github.com/rdkit/django-rdkit/blob/9da44191bf84bdf5f9f837783eead42774cf007c/django_rdkit/models/fields.py#L4

Indeed, it has been deprecated: https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

I have done a simple change on my fork that makes it work: https://github.com/roukydesbois/django-rdkit/commit/02ed8e2c074a22840d99957952917a210df4d948

But I'm pretty sure it won't work with previous versions of Django. So I'm not sure how to properly handle this 😄 

Thanks!

**Comment by rvianello** [comment]
Hi @roukydesbois 

thanks a lot for reporting the problem. Considering that we are in 2020, and support for python 2 was already dropped by both django and rdkit, I think it would probably make sense to simply remove these dependencies from this package too. I'll have a closer look during the next few days.

Best,
Riccardo

**Comment by rvianello** [comment]
@roukydesbois would you like to check if this PR https://github.com/rdkit/django-rdkit/pull/12 works for you?

**Comment by roukydesbois** [comment]
Hello @rvianello ! It looks like it does indeed, thanks!

**Comment by rvianello** [comment]
Great, thanks a lot for the quick feedback. I'll close this ticket once the PR is merged.
