### ISSUE TITLE
Django Gist Index

### ISSUE THREAD

**Issue by rustamzh** [rdkit/django-rdkit#15]
Is there any difference between using django-rdkit GiSTOperation manually writing migration and using GiST Index from [Django ORM](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/indexes/#gistindex).

From quick scan of generated SQL, it looks the same.

**Comment by rvianello** [comment]
Yes, I would expect the three to be equivalent. The main (probably the only) reason django-rdkit provides its own utility it that it predates the inclusion of the same functionality in django.

**Comment by rustamzh** [comment]
@rvianello, then it would probably make sense to drop it and adjust the docs. I can help with that.

**Comment by rvianello** [comment]
Hi @rustamzh I agree, it would probably make sense, and thanks a lot for the kind offer. No worries if you can't find the time, I'll try and look into this during the next weeks.

**Comment by rvianello** [comment]
thanks again for contributing a PR.
