### ISSUE TITLE
New release for conda-forge package

### ISSUE THREAD

**Issue by roukydesbois** [rdkit/django-rdkit#17]
Hello!

I have created a [recipe](https://github.com/conda-forge/django-rdkit-feedstock) in conda-forge for django-rdkit (so that it's easily installable in [chembience](https://github.com/chembience/chembience)). Unfortunately, conda-forge expects an archive in the recipe, so for now it contains v0.1.0 which is not compatible with Django 3. Could you please create a tag/a release for the current state of your code? Thanks!

**Comment by rvianello** [comment]
yes, sure, that sounds like a very nice idea, thanks a lot for this.
I increased the version number and created a new tag. Is this ok, or does conda-forge require an actual github Release?

**Comment by roukydesbois** [comment]
The tag is fine, conda-forge can work with github archives. Thanks a lot for the speedy response, I'll update the conda-forge accordingly!
