### ISSUE TITLE
Using Mol Field

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [rdkit/django-rdkit#24]
Hello! I am using rdkit in django app. The ```Compound``` model has a ```MolField```. 
I have trouble with using this implementation of ```get_prep_value``` in ```MolField```: 
```
    def get_prep_value(self, value):
        # convert the Molecule instance to the value used by the
        # db driver
        if isinstance(value, str):
            value = self.text_to_mol(value)
        if isinstance(value, Chem.Mol):
            value = memoryview(value.ToBinary())
        if value is None:
            return None
        return Func(value, function="mol_from_pkl")
```
But I fix it by change implementation to:
```
    def get_prep_value(self, value):
        # convert the Molecule instance to the value used by the
        # db driver
        if isinstance(value, str):
            value = self.text_to_mol(value)
        if value is None:
            return None
        return value.ToBinary()
```
Its fix my issue but I am new with rdkit and not shour what its correct way to serialize data to db.
Can someone answer me wich of method a more correct?

**Comment by rvianello** [comment]
As discussed in the [rdkit issue #5344](https://github.com/rdkit/rdkit/issues/5344), why your fix would work is a bit unclear to me, and the ticket is unfortunately not providing a clear description of the problem you had to solve. Could you please provide some additional information with regard to what query is executed, what trouble you experienced with the original implementation (what is more exactly the error, or unexpected behavior?) and what input `value` is passed?

Additional details about what version of django-rdkit was used, any modifications applying to it, versions of django, postgresql, rdkit (for both the web application and database cartridge) would also help.

**Comment by rvianello** [comment]
Thank you for sharing the additional information. I also realized now that the `get_prep_value` implementation you included in this ticket description is different from the one you posted with the original rdkit issue.

`bulk_update` works differently than a plain update (there are a few explicitly documented caveats), which is probably related to why `Func` may not work in this case. At the same time, `mol_from_pkl` might be unnecessary in the given context, but I'll try to perform a few tests during the next days.

**Comment by MichelML** [comment]
Gentle poke here :point_up:

**Comment by MichelML** [comment]
Gentle repoke here :point_up: (I know this is summer and you might be in vacation @rvianello ) , I'll just regularly check up here because this is sort of blocking for us at the moment

**Comment by rvianello** [comment]
@MichelML I hope I will be able to look into this in better detail starting tomorrow (sorry about the slow feedback, I'm just short on time)

**Comment by MichelML** [comment]
Thanks for the update @rvianello ! Totally understand

**Comment by rvianello** [comment]
@ivannnnnnnnnn @MichelML I've spent a bit of time on this during the past few days and I could easily reproduce the issue with the `bulk_update` method. Apparently, the new field values are passed directly to the db driver, which results in the `can't adapt type 'Func'` error message. On the other hand, not wrapping the value in a call to `mol_from_pkl` as you suggested, at the moment breaks some substructure lookup tests, and I'm therefore working on a refactoring that would consider the `Lookup` classes too.

**Comment by rvianello** [comment]
@ivannnnnnnnnn @MichelML I think PR #26 should fix the issue with the bulk update of MolField. It would be really great if you could find some time to test it and let me know how it works (I'll try to address the problem related to the client/server rdkit version separately).

**Comment by ivannnnnnnnnn** [comment]
> @ivannnnnnnnnn @MichelML I think PR #26 should fix the issue with the bulk update of MolField. It would be really great if you could find some time to test it and let me know how it works (I'll try to address the problem related to the client/server rdkit version separately).

Thank you. I will try to use this in my project on next week and write feedback here

**Comment by MichelML** [comment]
thanks a lot @rvianello!

I left a comment and approved the PR! Sorry for last week I was in vacation.

Thanks for taking the time again
