### ISSUE TITLE
Unique molfield error

### ISSUE THREAD

**Issue by paconius** [rdkit/django-rdkit#5]
I've been playing around with rdkit-django for a bit and think I've come across an issue which could use some documentation in the docs.

I observe that if you specify a MolField to be unique, the django code to check for uniqueness will raise an exception.
```
class Compound(models.Model):
    molecule = models.MolField(unique=True)
```
 This isn't an issue if you create new objects directly by using Compound.objects.create() (as in the tutorial). But it is a problem if you use the Django admin web interface to create new entries. The error occurs during the full_clean() of the input data. This makes a call to self._perform_unique_checks(...) in the base model, which issues a SQL query to check uniqueness. This causes the error below. It appears that the DB is choking on the comparison of two mol objects.
My first thought is to somehow override this behavior so that cxSMILES strings are compared instead; but I'm not advanced enough at this point to pull this off. Since uniqueness is such a basic concept, I'm guessing that this has been solved numerous times before. Adding the solution to the tutorial/docs would be great!

Thanks.

Django Version: | 2.1.1
-- | --
ProgrammingError|can't adapt type 'Mol'
...lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
Python Version:|3.6.5
rdkit Version:| '2018.03.4'
params | (<rdkit.Chem.rdchem.Mol object at 0x11576b8a0>,  <rdkit.Chem.rdchem.Mol object at 0x11576b8a0>)
self | <django.db.backends.utils.CursorDebugWrapper object at 0x1157f0f28>
sql | ('SELECT (1) AS "a" FROM "myapp_compound" WHERE "myapp_compound"."molecule" <@ %s '  'AND "myapp_compound"."molecule" @> %s  LIMIT 1')

**Comment by paconius** [comment]
Okay. I've looked into this a bit more and the root cause is that the rdkit cartridge does not allow anything other than SMILES to be used in queries. Therefore it appears that a big chunk of the fields.py code is not correct as it tries to feed mol objects to queries when only SMILES would be accepted.

**Comment by rvianello** [comment]
thank you for the report, I'll have a look into this and I'll try to post some additional comments.

**Comment by paconius** [comment]
After more digging, I was wrong -- the cartridge *does* allow pickled mol objects to be used in queries. The issue was that the current MolField functions weren't properly pickling them. I've got it working now by modifying the picking of objects.

**Comment by rvianello** [comment]
Thank you for submitting a PR, I was just about to suggest it. I'd leave this issue open until the PR is merged, if ok for you.

**Comment by paconius** [comment]
Took awhile to get it working for all tests. After all that the  key issue was a missing "mol_from_pkl" inside get_prep_value().

**Comment by rvianello** [comment]
Thank you the new version of the PR is not only more compact, but it also makes the intent clearer (and it fixes the tests, which was indeed an issue). I'll probably have a closer look at it again later today.
