### ISSUE TITLE
Where to set do_chiral_sss?

### ISSUE THREAD

**Issue by paconius** [rdkit/django-rdkit#7]
Hi again.

I want to ensure that the chiral_sss is set for my app. I tried to implement this by adding the code below to my app.py Config class (which gets run once at startup). 
```
from django_rdkit.config import config
config.do_chiral_sss = True
```
However, this gives an error, likely due to the connection not being correctly setup at the time the function is called.

> django.db.utils.ProgrammingError: unrecognized configuration parameter "rdkit.do_chiral_sss"

If I stick this code in some other function which is called after all initialization is complete (like a clean function for my model) it works fine.

My question then is, in your experience, where is the best place to put this code snippet so  it is run once, early on?

**Comment by paconius** [comment]
Ah, okay. I thought it was a database-level setting; but instead it is a connection-level setting that resets with each new connection. I'll pursue your suggestion. Thank you.

**Comment by byte-for-byte** [comment]
Hi paconius,
I have the same problem. Did you solve this back then?

**Comment by paconius** [comment]
> Hi paconius, I have the same problem. Did you solve this back then?

I was new to Django when @rvianello recommended using signals to force chiral_sss for each new database connection. As a result I was never able to make it work within the Django project. I ended up solving it by permanently setting the flag in the Postgres database itself. If you set the variable in the postgresql config file, then chiral matching will always be enabled an dyou don't need to mess with anything in the python/Django code to make it work correctly.

`cat << EOF >> $PGDATA/postgresql.conf
rdkit.do_chiral_sss = true #this turns on chiral substructure searching
EOF`

**Comment by byte-for-byte** [comment]
ok thanks. that is a possibility I will explore. Not sure if the users would like to switch to do_chiral_sss=False from time to time...

Well, I was surprised that this tutorial https://github.com/rdkit/django-rdkit/blob/master/docs/tutorial.rst describes how to set the flag, but it is either giving me the error you got or it is silently doing nothing, depending where I set the config flag.
Setting the flag directly in the database through psql works as you indicated (set rdkit.do_chiral_sss=true).

thanks for your help!
:)
